name: Banttan Canlı
favicon: null
layout_spectrum: 0.4404586888849735
typography_spectrum: 0.17220090026967227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6499756861012429
  lightness: 0.3985967680346221
  saturation: 0.32236052537336946
  rhythmicContrast: 0.3876998752821237
purpose: []
